### ISSUE TITLE
Jonathan is a troublemaker

### ISSUE THREAD

**Issue by itsholtz** [JonathanTravaglio/Jonathannah#1]
This is causing some serious issues with Jonathannah- needs to be resolved ASAP. Thoughts?

**Comment by JonathanTravaglio** [comment]
Thanks for the heads up Hannah.. I believe  this was Fixed in #3 .. Check it out and close the issue if all is good

**Comment by itsholtz** [comment]
Looks to be resolved ....
....for now.
