### ISSUE TITLE
We have a lack of Emojis/pictures

### ISSUE THREAD

**Issue by JonathanTravaglio** [JonathanTravaglio/Jonathannah#4]
our files are much too plain, we'll never become a super successfully company 😢

**Comment by itsholtz** [comment]
![jonathannah](https://user-images.githubusercontent.com/31223365/32670147-e4e98cd0-c610-11e7-97b4-7c2542e547ee.png)
What do you think?

**Comment by JonathanTravaglio** [comment]
Very good. Do you think this can be added to a file? Either the readme and/or some logo.txt file?
